name: Build Eleventy

on:
  push:
    branches:
      - gh-pages
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.21.3

      - name: Install dependencies & build
        run: |
          npm install
          npm install tailwindcss@3.3.2
          npm run build          

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          # 在仓库的 secrets 中设置了名为 GH_TOKEN 的令牌
          personal_token: ${{ secrets.GH_TOKEN }}
          cname: zestzhang.top